services:
  api:
    build: .
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      # monta todo o diretório src para garantir dataset + modelo dentro do container
      - ./src:/app/src:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
